modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Backup/issues"

[[mods]]
    modId="project_essentials_backup"
    version="1.15.2-1.0.1"
    displayName="Project Essentials Backup"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Backup/MC-1.15.2/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Backup"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Project Essentials Backup - additional module for Essentials;
    Just make server and client world backup by time or via command.
    '''

[[dependencies.projectessentialsbackup]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsbackup]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsbackup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
