modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Backup/issues"

[[mods]]
    modId="project_essentials_backup"
    version="${file.jarVersion}"
    displayName="Project Essentials Backup"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Backup/MC-1.15.2/updatev2.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Backup"
    credits="hujle, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Lightweight module for controlling the backup of the game world
    and configuration files on the server and in a single world.
    '''

[[dependencies.projectessentialsbackup]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsbackup]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialsbackup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
